package com.posthog.hogql;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import java.util.TimeZone;

public class HogQLConnection implements java.sql.Connection {

    private int networkTimeout;
    private boolean closed = false;
    private String apiUrl;
    private String apiKey;

    public HogQLConnection(String url, Properties info) {
        this.networkTimeout = 60;

        if (!url.startsWith("jdbc:hogql://")) {
            return;
        }

        String[] chunks = url.split("/");
        if (chunks.length < 4) {
            return;
        }

        String host = chunks[2], user = info.getProperty("user"), project = chunks[3], port = "443";
        if (host.length() == 0 || project.length() == 0) {
            return;
        }

        String[] userSplit = host.split("@");
        if (userSplit.length > 1) {
            user = userSplit[0];
            host = userSplit[1];
        }

        if (user == null) {
            return;
        }

        String[] portSplit = host.split(":");
        if (portSplit.length > 1) {
            host = portSplit[0];
            port = portSplit[1];
        }

        this.apiKey = user;
        this.apiUrl = (port.endsWith("443") ? "https://" : "http://") + host + (port.equals("443") ? "" : ":" + port) + "/api/projects/"+project+"/query";
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new HogQLStatement(this);
    }

    @Override
    public int getNetworkTimeout() {
        return this.networkTimeout;
    }

    @Override
    public void setNetworkTimeout(Executor executor, int networkTimeout) {
        this.networkTimeout = networkTimeout;
    }

    @Override
    public void abort(Executor executor) {
    }

    @Override
    public String getSchema() {
        return null;
    }

    @Override
    public void setSchema(String schema) {
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        return null;
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        return null;
    }

    @Override
    public String getClientInfo(String name) {
        return null;
    }

    @Override
    public Properties getClientInfo() {
        return null;
    }

    @Override
    public void setClientInfo(String name, String value) {

    }

    @Override
    public void setClientInfo(Properties properties) {

    }
    @Override
    public boolean isValid(int timeout) throws SQLException {
        if (timeout < 0) {
            throw new SQLException("Timeout value mustn't be less 0");
        }

        if (isClosed()) {
            return false;
        }

        return true;
    }


    @Override
    public void close() throws SQLException {
        closed = true;
    }

    @Override
    public boolean isClosed() {
        return closed;
    }


    @Override
    public Clob createClob() {
        return null;
    }

    @Override
    public Blob createBlob() {
        return null;
    }

    @Override
    public NClob createNClob() {
        return null;
    }

    @Override
    public SQLXML createSQLXML() {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException{
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public PreparedStatement prepareStatement(String sql,
                                              int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    public HogQLStatement createStatement(int resultSetType) {
        return new HogQLStatement(this);
    }

    @Override
    public HogQLStatement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new HogQLStatement(this);
    }

    @Override
    public HogQLStatement createStatement(int resultSetType, int resultSetConcurrency,
                                               int resultSetHoldability) throws SQLException {
        return new HogQLStatement(this);
    }
    public TimeZone getTimeZone() {
        return null;
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void setAutoCommit(boolean autoCommit) {

    }

    @Override
    public boolean getAutoCommit() {
        return false;
    }

    @Override
    public void commit() {

    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public CallableStatement prepareCall(String sql,
                                         int resultSetType,
                                         int resultSetConcurrency,
                                         int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void rollback() {

    }

    @Override
    public void rollback(Savepoint savepoint) {

    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public Map<String, Class<?>> getTypeMap() {
        return null;
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) {

    }

    @Override
    public void setHoldability(int holdability) {

    }

    @Override
    public int getHoldability() {
        return 0;
    }
    @Override
    public SQLWarning getWarnings() {
        return null;
    }

    @Override
    public void clearWarnings() {

    }

    @Override
    public void setTransactionIsolation(int level) {

    }

    @Override
    public int getTransactionIsolation() {
        return TRANSACTION_NONE;
    }

    @Override
    public void setReadOnly(boolean readOnly) {

    }

    @Override
    public boolean isReadOnly() {
        return true;
    }

    @Override
    public void setCatalog(String catalog) {
        // properties.setDatabase(catalog);
    }

    @Override
    public String getCatalog() {
        // return properties.getDatabase();
        return null;
    }


    @Override
    public DatabaseMetaData getMetaData() {
        return null; // new ClickHouseDatabaseMetadata(url, this);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isAssignableFrom(getClass());
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isAssignableFrom(getClass())) {
            return iface.cast(this);
        }
        throw new SQLException("Cannot unwrap to " + iface.getName());
    }

    public String getApiUrl() {
        return apiUrl; // "http://localhost:8000/api/projects/1/query";
    }

    public String getApiKey() {
        return apiKey; // "phx_zBXe4XYk4UV5Rg4k0zZXcodlokNpiX4aHkWly7oaYwq";
    }
}
